version: '3'
services:
  zookeeper:
    image: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOO_MY_ID: 1
    restart: always
    volumes:
      - ./storage/zoo/data:/data
      - ./storage/zoo/datalog:/datalog
    stop_grace_period: 60s

  kafka-1:
    image: wurstmeister/kafka:2.12-2.5.0
    container_name: kafka-1
    depends_on: 
      - zookeeper
    ports:
      - "9095:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: C02CW3ZWMD6T
      KAFKA_ADVERTISED_PORT: 9095
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LOG_DIRS: /kafka/logs
      KAFKA_BROKER_ID: 501
      KAFKA_offsets_topic_replication_factor: 3
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./storage/kafka-1:/kafka
    stop_grace_period: 60s

  kafka-2:
    image: wurstmeister/kafka:2.12-2.5.0
    container_name: kafka-2
    depends_on: 
      - zookeeper
    ports:
      - "9096:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: C02CW3ZWMD6T
      KAFKA_ADVERTISED_PORT: 9096
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LOG_DIRS: /kafka/logs
      KAFKA_BROKER_ID: 502
      KAFKA_offsets_topic_replication_factor: 3
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./storage/kafka-2:/kafka
    stop_grace_period: 60s

  kafka-3:
    image: wurstmeister/kafka:2.12-2.5.0
    hostname: kafka-3
    container_name: kafka-3
    depends_on: 
      - zookeeper
    ports:
      - "9097:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: C02CW3ZWMD6T
      KAFKA_ADVERTISED_PORT: 9097
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LOG_DIRS: /kafka/logs
      KAFKA_BROKER_ID: 503
      KAFKA_offsets_topic_replication_factor: 3
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./storage/kafka-3:/kafka
    stop_grace_period: 60s

  kafka-connector:
    image: wurstmeister/kafka:2.12-2.5.0
    container_name: kafka-connector
    depends_on: 
      - zookeeper
      - kafka-1
      - kafka-2
      - kafka-3
    ports:
      - "8083:8083"
    environment:
      KAFKA_HEAP_OPTS: "-Xms256M -Xmx3G"
    restart: always
    volumes:
      - ./snowflake-kafka-connector-1.5.2.jar:/usr/local/share/kafka/plugins/snowflake-kafka-connector-1.5.2.jar
      - ./bc-fips-1.0.2.jar:/opt/kafka/libs/bc-fips-1.0.2.jar
      - ./bcpkix-fips-1.0.3.jar:/opt/kafka/libs/bcpkix-fips-1.0.3.jar
      - ./snowflake-jdbc-3.13.0.jar:/opt/kafka/libs/snowflake-jdbc-3.13.0.jar
      - ./connect-distributed.properties:/connect-distributed.properties
    command: ["connect-distributed.sh", "/connect-distributed.properties"]
    stop_grace_period: 60s